REPLACE INTO lab (code, name, contact, country, email, language, labnotes) VALUES 
('BEL_001', NULL, 'Nicolas Van der Linden BEL_001', 'BE', 'nivdlind@ulb.ac.be', 'French', ''),
('FRA_003', NULL, 'Hans IJzerman; Lison Neyroud FRA_003', 'FR', 'h.ijzerman@gmail.com', 'French', ''),
('FRA_004', NULL, 'Coralie Chevallier, Lou Safra (FRA_004)', 'FR', 'coralie.chevallier@gmail.com', 'French', ''),
('FRA_005', NULL, 'Armand Chatard', 'FR', 'armand.chatard@univ-poitiers.fr', 'French', ''),
('FRA_006', NULL, 'Kaminski Gwenaël FRA_006', 'FR', 'gwenael.kaminski@univ-tlse2.fr', 'French', ''),
('SUI_003', NULL, 'Evie Vergauwe, Kim Uittenhove SUI_003', 'CH', 'Evie Vergauwe <Evie.Vergauwe@unige.ch>', 'French', ''),
('AUS_007', NULL, 'Barnaby Dixson AUS_007', 'AU', 'b.dixson@uq.edu.au', 'English', ''),
('AUS_006', NULL, 'David White AUS_006', 'AU', 'david.white@unsw.edu.au', 'English', ''),
('AUS_004', NULL, 'Ian Stephen AUS_004', 'AU', 'Ian Stephen <ian.stephen@mq.edu.au>', 'English', ''),
('AUS_005', NULL, 'Khandis Blake AUS_005', 'AU', 'k.blake@unsw.edu.au', 'English', ''),
('AUS_006', NULL, 'Monica Koehn, Ceylan Okan AUS_006', 'AU', 'Monica Koehn <koehn.monica@gmail.com> Ceylan Okan <C.Okan@westernsydney.edu.au> <jayokanc@gmail.com>', 'English', ''),
('AUS_008', NULL, 'Taylor Gogan, Julian Oldmeadow, Jennifer Beaudry AUS_008', 'AU', 'TGOGAN@swin.edu.au; jbeaudry@swin.edu.au; joldmeadow@swin.edu.au', 'English', ''),
('CAN_003', NULL, 'Daniel Ansari CAN_003', 'CA', 'Daniel.ansari@gmail.com', 'English', ''),
('CAN_008', NULL, 'Eric Hehman, Sally Xie (CAN_008)', 'CA', 'Eric Hehman <Eric.Hehman@psych.ryerson.ca>, sally.xie@psych.ryerson.ca', 'English', ''),
('CAN_015', NULL, 'Hause Lin, Michael Inzlicht (CAN_015)', 'CA', 'hause.lin@mail.utoronto.ca, michael.inzlicht@utoronto.ca', 'English', ''),
('CAN_001', NULL, 'Jill A. Jacobson CAN_001', 'CA', 'jill.jacobosn@queensu.ca', 'English', ''),
('CAN_018', NULL, 'Tripat Gill (CAN_018)', 'CA', 'tgill@wlu.ca', 'English', ''),
('CAN_028', NULL, 'David Feinberg', 'CA', 'feinberg@mcmaster.ca', 'English', ''),
('CAN_029', NULL, 'Marie Armstrong', 'CA', 'armstrmm@mcmaster.ca', 'English', ''),
('DNK_001', NULL, 'Christoph Schild, Karolina Scigala, Ingo Zettler', 'DK', 'fhv726@ku.dk', 'English', ''),
('KEN_001', NULL, 'Jang Ken_001', 'KE', 'david.clarance@busaracenter.org, chaning.jang@busaracenter.org', 'English', ''),
('MAS_002', NULL, 'Ai-Suan Lee MAS_002', 'MY', 'lee.aisuan@gmail.com', 'English', ''),
('MAS_003', NULL, 'Chrystalle B. Y. Tan MAS_003', 'MY', 'tan.chrystalle@gmail.com', 'English', ''),
('MAS_004', NULL, 'Steve Janssen MAS_004', 'MY', 'steve.janssen@nottingham.edu.my', 'English', ''),
('MAS_001', NULL, 'Tan Kok Wei MAS_001', 'MY', 't.kokwei@reading.edu.my', 'English', ''),
('NED_008', NULL, 'Dongning Ren NED_008', 'NL', 'd.ren@uvt.nl', 'English', ''),
('NZL_002', NULL, 'Matt Crawford NZL_002', 'NZ', 'Matt.Crawford@vuw.ac.nz', 'English', ''),
('NZL_001', NULL, 'Michael Philipp NZL_001', 'NZ', 'M.Philipp@massey.ac.nz', 'English', ''),
('RSA_002', NULL, 'Casper van Zyl', 'ZA', 'caspervz@uj.ac.za', 'English', ''),
('RSA_001', NULL, 'Vinet Coetzee RSA_001', 'ZA', 'vinet.coetzee@up.ac.za', 'English', ''),
('UK_022', NULL, 'Alasdair Gordon-Finlayson, Graham Smith', 'GB', 'Alasdair.Gordon-Finlayson@northampton.ac.uk', 'English', ''),
('UK_011', NULL, 'Blair Saunders and Ben Vincent UK_011', 'GB', 'b.z.saunders@dundee.ac.uk', 'english', ''),
('UK_016', NULL, 'Jones & DeBruine (UK_016)', 'GB', 'ben.jones@glasgow.ac.uk, lisa.debruine@glasgow.ac.uk', 'english', ''),
('UK_018', NULL, 'Kay Ritchie UK_018', 'GB', 'kritchie@lincoln.ac.uk', 'English', ''),
('UK_024', NULL, 'Martin Thirkettle UK_024', 'GB', 'm.thirkettle@shu.ac.uk', 'English', ''),
('UK_001', NULL, 'Melissa Colloff & Heather Flowe UK_001', 'GB', 'M.colloff@bham.ac.uk; h.flowe@bham.ac.uk', 'English', ''),
('UK_005', NULL, 'Miroslav Sirota, Guyan Sloane UK_005', 'GB', 'msirota@essex.ac.uk', 'English', ''),
('UK_019', NULL, 'Tara Marshall UK_019', 'GB', 'Tara.Marshall@brunel.ac.uk', 'English', ''),
('UK_006', NULL, 'Thomas Rhys Evans UK_006', 'GB', 'ab6443@coventry.ac.uk', 'English', ''),
('USA_033', NULL, 'Carmel Levitan USA_033', 'US', 'levitan@oxy.edu', 'English', ''),
('PSA_001', NULL, 'Chris Chartier PSA_001', 'US', 'cchartie@ashland.edu', 'English', ''),
('USA_005', NULL, 'Cody Christopherson USA_005', 'US', 'christoc1@sou.edu', 'English', ''),
('USA_065', NULL, 'Daniel Storage USA_065', 'US', 'sabbystorage@gmail.com', 'English', ''),
('USA_054', NULL, 'Dustin Calvillo USA_054', 'US', 'dcalvill@csusm.edu', 'English', ''),
('USA_050', NULL, 'Gwen Gardiner USA_050', 'US', 'ggard001@ucr.edu', 'English', ''),
('USA_051', NULL, 'Jeremy Miller USA_051', 'US', 'millerj@willamette.edu', 'English', ''),
('USA_011', NULL, 'Kathleen Schmidt USA_011', 'US', 'kathleenschmidt1@gmail.com', 'English', ''),
('USA_001', NULL, 'Martin Seehuus USA_001', 'US', 'mseehuus@middlebury.edu', 'English', ''),
('USA_025', NULL, 'Michael Andreychik USA_025', 'US', 'm.andreychik@gmail.com', 'English', ''),
('USA_031', NULL, 'Nicholas A. Coles USA_031', 'US', 'colesn@vols.utk.edu', 'English', ''),
('USA_075', NULL, 'Nicholas Michalak USA_075', 'US', 'nickmm@umich.edu', 'English', ''),
('USA_014', NULL, 'Nikki Legate USA_014', 'US', 'nlegate@iit.edu', 'English', ''),
('USA_016', NULL, 'Randy McCarthy USA_016', 'US', 'rmccarthy3@niu.edu', 'English', ''),
('USA_042', NULL, 'Yarrow Dunham, Xin Yang USA_042', 'US', 'yarrow.dunham@yale.edu, xin.yang@yale.edu', 'English', ''),
('USA_003', NULL, 'Amanda Hahn USA_003', 'US', 'amanda.hahn@humboldt.edu', 'English', ''),
('USA_045', NULL, 'Ernest Baskin USA_045', 'US', 'ebaskin@sju.edu', 'English', ''),
('USA_036', NULL, 'Heather Urry USA_036', 'US', 'heather.urry@tufts.edu', 'English', ''),
('USE_067', NULL, 'Jack Arnal USA_067', 'US', 'Jarnal@mcdaniel.edu', 'English', ''),
('USA_020', NULL, 'William Chopik USA_020', 'US', 'chopikwi@msu.edu', 'English', ''),
('USA_043', NULL, 'Alexander Danvers USA_043', 'US', 'alexander.danvers@gmail.com', 'English', ' Syrians (many now displaced; online data collection)'),
('USA_061', NULL, 'Corey Cook USA_061', 'US', 'cookcn@plu.edu', 'English', ''),
('USA_113', NULL, 'Ben Balas', 'US', 'benjamin.balas@ndsu.edu', 'English', ''),
('USA_117', NULL, 'Erin O\'Mara', 'US', 'eomara1@udayton.edu', 'English', ''),
('USA_039', NULL, 'John Paul Wilson USA_039', 'US', 'wilsonjoh@montclair.edu', 'English', ''),
('USA_055', NULL, 'John Protzko USA_055', 'US', 'John Protzko <protzko@gmail.com>', 'English', ''),
('USA_030', NULL, 'Leigh Ann Vaughn USA_030', 'US', 'lvaughn@ithaca.edu', 'English', ''),
('USA_026', NULL, 'Patrick Forscher USA_026', 'US', 'forscher@uark.edu', 'English', ''),
('USA_027', NULL, 'Brady Wiggins USA_027', 'US', 'wigginsb@byui.edu', 'English', ''),
('USA_083', NULL, 'Brooke Bennett-Day', 'US', 'bbennettday@wesleyancollege.edu', 'English', ''),
('USA_114', NULL, 'Christopher Thorstenson', 'US', 'c.thorstenson@rochester.edu', 'English', ''),
('USA_115', NULL, 'Jordan Suchow', 'US', 'jordan.suchow@stevens.edu', 'English', ''),
('USA_116', NULL, 'Jon Freeman', 'US', 'jon.freeman@nyu.edu', 'English', ''),
('AUS_008', NULL, 'Jennifer L Beaudry AUS_008', 'NZ', 'jbeaudry@swin.edu.au', 'English', ''),
('USA_034', NULL, 'Justin Keene USA_034', 'US', 'justin.r.keene@ttu.edu', 'English', ''),
('ITA_001', NULL, 'Marco Tullio Liuzza ITA_001', 'IT', 'liuzza@unicz.it', 'Italian', ''),
('ITA_003', NULL, 'Michelangelo Vianello (ITA_003)', 'IT', 'michelangelo.vianello@unipd.it', 'Italian', '');
