UPDATE exp SET res_name='PSA1_ENG_Agg_1', name='Rating aggressiveness', instructions='You will see 120 faces. Please indicate how aggressive you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How aggressive (i.e., inclined to behave in a hostile fashion) is this person?' WHERE id=1;
UPDATE exp SET res_name='PSA1_ENG_Att_1', name='Rating attractiveness', instructions='You will see 120 faces. Please indicate how attractive you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How attractive (i.e., appealing to the senses through beauty, form, character, etc) is this person?' WHERE id=2;
UPDATE exp SET res_name='PSA1_ENG_Car_1', name='Rating caringness', instructions='You will see 120 faces. Please indicate how caring you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How caring (i.e., feeling or showing compassion) is this person?' WHERE id=3;
UPDATE exp SET res_name='PSA1_ENG_Con_1', name='Rating confidence', instructions='You will see 120 faces. Please indicate how confident you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How confident (i.e., sure of oneself; having no uncertainty about ones own abilities) is this person?' WHERE id=4;
UPDATE exp SET res_name='PSA1_ENG_Dom_1', name='Rating dominance', instructions='You will see 120 faces. Please indicate how dominant you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How dominant (i.e., strong; important) is this person?' WHERE id=5;
UPDATE exp SET res_name='PSA1_ENG_Emo_1', name='Rating emotional stability', instructions='You will see 120 faces. Please indicate how emotionall stable you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How emotionally stable (i.e., not subject to emotional instability or illness; sane; mentally sound) is this person?' WHERE id=6;
UPDATE exp SET res_name='PSA1_ENG_Unh_1', name='Rating unhappiness', instructions='You will see 120 faces. Please indicate how unhappy you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How unhappy (i.e., not joyful; sad or depressed) is this person?' WHERE id=7;
UPDATE exp SET res_name='PSA1_ENG_Int_1', name='Rating intelligence', instructions='You will see 120 faces. Please indicate how intelligent you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How intelligent (i.e., having a good understanding or a high mental capacity) is this person?' WHERE id=8;
UPDATE exp SET res_name='PSA1_ENG_Mea_1', name='Rating meanness', instructions='You will see 120 faces. Please indicate how mean you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How mean (i.e., offensive, selfish, or unaccomodating; nasty; malicious) is this person?' WHERE id=9;
UPDATE exp SET res_name='PSA1_ENG_Res_1', name='Rating responsibility', instructions='You will see 120 faces. Please indicate how responsible you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How responsible (i.e., able to take rational decisions without supervision; accountable for ones own actions) is this person?' WHERE id=10;
UPDATE exp SET res_name='PSA1_ENG_Soc_1', name='Rating sociability', instructions='You will see 120 faces. Please indicate how sociable you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How sociable (i.e., friendly or agreeable in company; companionable) is this person?' WHERE id=11;
UPDATE exp SET res_name='PSA1_ENG_Tru_1', name='Rating trustworthiness', instructions='You will see 120 faces. Please indicate how trustworthy you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How trustworthy (i.e., deserving of confidence; dependable; reliable) is this person?' WHERE id=12;
UPDATE exp SET res_name='PSA1_ENG_Wei_1', name='Rating weirdness', instructions='You will see 120 faces. Please indicate how weird you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How weird (i.e., strange or bizarre) is this person?' WHERE id=13;
UPDATE exp SET res_name='PSA1_ENG_Old_1', name='Rating age', instructions='You will see 120 faces. Please indicate how old you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How old (i.e., having greater age; not young) is this person?' WHERE id=14;
UPDATE exp SET res_name='PSA1_ENG_Agg_2', name='Rating aggressiveness', instructions='You will see 120 faces. Please indicate how aggressive you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How aggressive (i.e., inclined to behave in a hostile fashion) is this person?' WHERE id=15;
UPDATE exp SET res_name='PSA1_ENG_Att_2', name='Rating attractiveness', instructions='You will see 120 faces. Please indicate how attractive you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How attractive (i.e., appealing to the senses through beauty, form, character, etc) is this person?' WHERE id=16;
UPDATE exp SET res_name='PSA1_ENG_Car_2', name='Rating caringness', instructions='You will see 120 faces. Please indicate how caring you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How caring (i.e., feeling or showing compassion) is this person?' WHERE id=17;
UPDATE exp SET res_name='PSA1_ENG_Con_2', name='Rating confidence', instructions='You will see 120 faces. Please indicate how confident you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How confident (i.e., sure of oneself; having no uncertainty about ones own abilities) is this person?' WHERE id=18;
UPDATE exp SET res_name='PSA1_ENG_Dom_2', name='Rating dominance', instructions='You will see 120 faces. Please indicate how dominant you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How dominant (i.e., strong; important) is this person?' WHERE id=19;
UPDATE exp SET res_name='PSA1_ENG_Emo_2', name='Rating emotional stability', instructions='You will see 120 faces. Please indicate how emotionall stable you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How emotionally stable (i.e., not subject to emotional instability or illness; sane; mentally sound) is this person?' WHERE id=20;
UPDATE exp SET res_name='PSA1_ENG_Unh_2', name='Rating unhappiness', instructions='You will see 120 faces. Please indicate how unhappy you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How unhappy (i.e., not joyful; sad or depressed) is this person?' WHERE id=21;
UPDATE exp SET res_name='PSA1_ENG_Int_2', name='Rating intelligence', instructions='You will see 120 faces. Please indicate how intelligent you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How intelligent (i.e., having a good understanding or a high mental capacity) is this person?' WHERE id=22;
UPDATE exp SET res_name='PSA1_ENG_Mea_2', name='Rating meanness', instructions='You will see 120 faces. Please indicate how mean you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How mean (i.e., offensive, selfish, or unaccomodating; nasty; malicious) is this person?' WHERE id=23;
UPDATE exp SET res_name='PSA1_ENG_Res_2', name='Rating responsibility', instructions='You will see 120 faces. Please indicate how responsible you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How responsible (i.e., able to take rational decisions without supervision; accountable for ones own actions) is this person?' WHERE id=24;
UPDATE exp SET res_name='PSA1_ENG_Soc_2', name='Rating sociability', instructions='You will see 120 faces. Please indicate how sociable you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How sociable (i.e., friendly or agreeable in company; companionable) is this person?' WHERE id=25;
UPDATE exp SET res_name='PSA1_ENG_Tru_2', name='Rating trustworthiness', instructions='You will see 120 faces. Please indicate how trustworthy you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How trustworthy (i.e., deserving of confidence; dependable; reliable) is this person?' WHERE id=26;
UPDATE exp SET res_name='PSA1_ENG_Wei_2', name='Rating weirdness', instructions='You will see 120 faces. Please indicate how weird you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How weird (i.e., strange or bizarre) is this person?' WHERE id=27;
UPDATE exp SET res_name='PSA1_ENG_Old_2', name='Rating age', instructions='You will see 120 faces. Please indicate how old you think each person is by clicking on the button above the face that best represents your judgment.', question = 'How old (i.e., having greater age; not young) is this person?' WHERE id=28;


REPLACE INTO set_items (set_id, item_type, item_id, item_n) VALUES 
(2, 'exp', 1, 1),
(3, 'exp', 2, 1),
(4, 'exp', 3, 1),
(5, 'exp', 4, 1),
(6, 'exp', 5, 1),
(7, 'exp', 6, 1),
(8, 'exp', 7, 1),
(9, 'exp', 8, 1),
(10, 'exp', 9, 1),
(11, 'exp', 10, 1),
(12, 'exp', 11, 1),
(13, 'exp', 12, 1),
(14, 'exp', 13, 1),
(15, 'exp', 14, 1),
(2, 'exp', 1, 2),
(3, 'exp', 2, 2),
(4, 'exp', 3, 2),
(5, 'exp', 4, 2),
(6, 'exp', 5, 2),
(7, 'exp', 6, 2),
(8, 'exp', 7, 2),
(9, 'exp', 8, 2),
(10, 'exp', 9, 2),
(11, 'exp', 10, 2),
(12, 'exp', 11, 2),
(13, 'exp', 12, 2),
(14, 'exp', 13, 2),
(15, 'exp', 14, 2),
(16, 'set', 2, 1),
(16, 'set', 3, 2),
(16, 'set', 4, 3),
(16, 'set', 5, 4),
(16, 'set', 6, 5),
(16, 'set', 7, 6),
(16, 'set', 8, 7),
(16, 'set', 9, 8),
(16, 'set', 10, 9),
(16, 'set', 11, 10),
(16, 'set', 12, 11),
(16, 'set', 13, 12),
(16, 'set', 14, 13),
(16, 'set', 15, 14),
(1, 'set', 16, 1);

REPLACE INTO access (type, id, user_id) VALUES
('exp', 1, 1),
('exp', 2, 1),
('exp', 3, 1),
('exp', 4, 1),
('exp', 5, 1),
('exp', 6, 1),
('exp', 7, 1),
('exp', 8, 1),
('exp', 9, 1),
('exp', 10, 1),
('exp', 11, 1),
('exp', 12, 1),
('exp', 13, 1),
('exp', 14, 1),
('exp', 1, 1),
('exp', 2, 1),
('exp', 3, 1),
('exp', 4, 1),
('exp', 5, 1),
('exp', 6, 1),
('exp', 7, 1),
('exp', 8, 1),
('exp', 9, 1),
('exp', 10, 1),
('exp', 11, 1),
('exp', 12, 1),
('exp', 13, 1),
('exp', 14, 1),
('sets', 2, 1),
('sets', 3, 1),
('sets', 4, 1),
('sets', 5, 1),
('sets', 6, 1),
('sets', 7, 1),
('sets', 8, 1),
('sets', 9, 1),
('sets', 10, 1),
('sets', 11, 1),
('sets', 12, 1),
('sets', 13, 1),
('sets', 14, 1),
('sets', 15, 1),
('sets', 16, 1),
('sets', 1, 1);

REPLACE INTO sets (res_name, name, id, create_date, type) VALUES 
('PSA1_ENG_Agg', 'Rating aggressiveness' ,2, NOW(), 'fixed'),
('PSA1_ENG_Att', 'Rating attractiveness' ,3, NOW(), 'fixed'),
('PSA1_ENG_Car', 'Rating caringness' ,4, NOW(), 'fixed'),
('PSA1_ENG_Con', 'Rating confidence' ,5, NOW(), 'fixed'),
('PSA1_ENG_Dom', 'Rating dominance' ,6, NOW(), 'fixed'),
('PSA1_ENG_Emo', 'Rating emotional stability' ,7, NOW(), 'fixed'),
('PSA1_ENG_Unh', 'Rating unhappiness' ,8, NOW(), 'fixed'),
('PSA1_ENG_Int', 'Rating intelligence' ,9, NOW(), 'fixed'),
('PSA1_ENG_Mea', 'Rating meanness' ,10, NOW(), 'fixed'),
('PSA1_ENG_Res', 'Rating responsibility' ,11, NOW(), 'fixed'),
('PSA1_ENG_Soc', 'Rating sociability' ,12, NOW(), 'fixed'),
('PSA1_ENG_Tru', 'Rating trustworthiness' ,13, NOW(), 'fixed'),
('PSA1_ENG_Wei', 'Rating weirdness' ,14, NOW(), 'fixed'),
('PSA1_ENG_Old', 'Rating age' ,15, NOW(), 'fixed'),
('PSA1_ENG_Ratings', 'Ratings' ,2, NOW(), 'one_random'),
('PSA1_ENG', 'Face Study' ,3, NOW(), 'fixed');

REPLACE INTO project (id, res_name, name, url, blurb) VALUES
(1, 'PSA1_ENG_ENG_test', 'Face Study (ENG_test)','psa1_ENG_test', 'PSA1 Study: ENG_test' ),
(2, 'PSA1_ENG_AUS_007', 'Face Study (AUS_007)','psa1_AUS_007', 'PSA1 Study: AUS_007' ),
(3, 'PSA1_ENG_AUS_011', 'Face Study (AUS_011)','psa1_AUS_011', 'PSA1 Study: AUS_011' ),
(4, 'PSA1_ENG_AUS_004', 'Face Study (AUS_004)','psa1_AUS_004', 'PSA1 Study: AUS_004' ),
(5, 'PSA1_ENG_AUS_005', 'Face Study (AUS_005)','psa1_AUS_005', 'PSA1 Study: AUS_005' ),
(6, 'PSA1_ENG_AUS_006', 'Face Study (AUS_006)','psa1_AUS_006', 'PSA1 Study: AUS_006' ),
(7, 'PSA1_ENG_AUS_008', 'Face Study (AUS_008)','psa1_AUS_008', 'PSA1 Study: AUS_008' ),
(8, 'PSA1_ENG_CAN_003', 'Face Study (CAN_003)','psa1_CAN_003', 'PSA1 Study: CAN_003' ),
(9, 'PSA1_ENG_CAN_008', 'Face Study (CAN_008)','psa1_CAN_008', 'PSA1 Study: CAN_008' ),
(10, 'PSA1_ENG_CAN_015', 'Face Study (CAN_015)','psa1_CAN_015', 'PSA1 Study: CAN_015' ),
(11, 'PSA1_ENG_CAN_001', 'Face Study (CAN_001)','psa1_CAN_001', 'PSA1 Study: CAN_001' ),
(12, 'PSA1_ENG_CAN_018', 'Face Study (CAN_018)','psa1_CAN_018', 'PSA1 Study: CAN_018' ),
(13, 'PSA1_ENG_CAN_028', 'Face Study (CAN_028)','psa1_CAN_028', 'PSA1 Study: CAN_028' ),
(14, 'PSA1_ENG_CAN_029', 'Face Study (CAN_029)','psa1_CAN_029', 'PSA1 Study: CAN_029' ),
(15, 'PSA1_ENG_DNK_001', 'Face Study (DNK_001)','psa1_DNK_001', 'PSA1 Study: DNK_001' ),
(16, 'PSA1_ENG_KEN_001', 'Face Study (KEN_001)','psa1_KEN_001', 'PSA1 Study: KEN_001' ),
(17, 'PSA1_ENG_MAS_002', 'Face Study (MAS_002)','psa1_MAS_002', 'PSA1 Study: MAS_002' ),
(18, 'PSA1_ENG_MAS_003', 'Face Study (MAS_003)','psa1_MAS_003', 'PSA1 Study: MAS_003' ),
(19, 'PSA1_ENG_MAS_004', 'Face Study (MAS_004)','psa1_MAS_004', 'PSA1 Study: MAS_004' ),
(20, 'PSA1_ENG_MAS_001', 'Face Study (MAS_001)','psa1_MAS_001', 'PSA1 Study: MAS_001' ),
(21, 'PSA1_ENG_NED_008', 'Face Study (NED_008)','psa1_NED_008', 'PSA1 Study: NED_008' ),
(22, 'PSA1_ENG_NZL_002', 'Face Study (NZL_002)','psa1_NZL_002', 'PSA1 Study: NZL_002' ),
(23, 'PSA1_ENG_NZL_001', 'Face Study (NZL_001)','psa1_NZL_001', 'PSA1 Study: NZL_001' ),
(24, 'PSA1_ENG_RSA_002', 'Face Study (RSA_002)','psa1_RSA_002', 'PSA1 Study: RSA_002' ),
(25, 'PSA1_ENG_RSA_001', 'Face Study (RSA_001)','psa1_RSA_001', 'PSA1 Study: RSA_001' ),
(26, 'PSA1_ENG_UK_022', 'Face Study (UK_022)','psa1_UK_022', 'PSA1 Study: UK_022' ),
(27, 'PSA1_ENG_UK_011', 'Face Study (UK_011)','psa1_UK_011', 'PSA1 Study: UK_011' ),
(28, 'PSA1_ENG_UK_016', 'Face Study (UK_016)','psa1_UK_016', 'PSA1 Study: UK_016' ),
(29, 'PSA1_ENG_UK_018', 'Face Study (UK_018)','psa1_UK_018', 'PSA1 Study: UK_018' ),
(30, 'PSA1_ENG_UK_024', 'Face Study (UK_024)','psa1_UK_024', 'PSA1 Study: UK_024' ),
(31, 'PSA1_ENG_UK_001', 'Face Study (UK_001)','psa1_UK_001', 'PSA1 Study: UK_001' ),
(32, 'PSA1_ENG_UK_005', 'Face Study (UK_005)','psa1_UK_005', 'PSA1 Study: UK_005' ),
(33, 'PSA1_ENG_UK_019', 'Face Study (UK_019)','psa1_UK_019', 'PSA1 Study: UK_019' ),
(34, 'PSA1_ENG_UK_006', 'Face Study (UK_006)','psa1_UK_006', 'PSA1 Study: UK_006' ),
(35, 'PSA1_ENG_USA_033', 'Face Study (USA_033)','psa1_USA_033', 'PSA1 Study: USA_033' ),
(36, 'PSA1_ENG_PSA_001', 'Face Study (PSA_001)','psa1_PSA_001', 'PSA1 Study: PSA_001' ),
(37, 'PSA1_ENG_USA_005', 'Face Study (USA_005)','psa1_USA_005', 'PSA1 Study: USA_005' ),
(38, 'PSA1_ENG_USA_065', 'Face Study (USA_065)','psa1_USA_065', 'PSA1 Study: USA_065' ),
(39, 'PSA1_ENG_USA_054', 'Face Study (USA_054)','psa1_USA_054', 'PSA1 Study: USA_054' ),
(40, 'PSA1_ENG_USA_050', 'Face Study (USA_050)','psa1_USA_050', 'PSA1 Study: USA_050' ),
(41, 'PSA1_ENG_USA_051', 'Face Study (USA_051)','psa1_USA_051', 'PSA1 Study: USA_051' ),
(42, 'PSA1_ENG_USA_011', 'Face Study (USA_011)','psa1_USA_011', 'PSA1 Study: USA_011' ),
(43, 'PSA1_ENG_USA_001', 'Face Study (USA_001)','psa1_USA_001', 'PSA1 Study: USA_001' ),
(44, 'PSA1_ENG_USA_025', 'Face Study (USA_025)','psa1_USA_025', 'PSA1 Study: USA_025' ),
(45, 'PSA1_ENG_USA_031', 'Face Study (USA_031)','psa1_USA_031', 'PSA1 Study: USA_031' ),
(46, 'PSA1_ENG_USA_075', 'Face Study (USA_075)','psa1_USA_075', 'PSA1 Study: USA_075' ),
(47, 'PSA1_ENG_USA_014', 'Face Study (USA_014)','psa1_USA_014', 'PSA1 Study: USA_014' ),
(48, 'PSA1_ENG_USA_016', 'Face Study (USA_016)','psa1_USA_016', 'PSA1 Study: USA_016' ),
(49, 'PSA1_ENG_USA_042', 'Face Study (USA_042)','psa1_USA_042', 'PSA1 Study: USA_042' ),
(50, 'PSA1_ENG_USA_003', 'Face Study (USA_003)','psa1_USA_003', 'PSA1 Study: USA_003' ),
(51, 'PSA1_ENG_USA_045', 'Face Study (USA_045)','psa1_USA_045', 'PSA1 Study: USA_045' ),
(52, 'PSA1_ENG_USA_036', 'Face Study (USA_036)','psa1_USA_036', 'PSA1 Study: USA_036' ),
(53, 'PSA1_ENG_USA_067', 'Face Study (USA_067)','psa1_USA_067', 'PSA1 Study: USA_067' ),
(54, 'PSA1_ENG_USA_020', 'Face Study (USA_020)','psa1_USA_020', 'PSA1 Study: USA_020' ),
(55, 'PSA1_ENG_USA_043', 'Face Study (USA_043)','psa1_USA_043', 'PSA1 Study: USA_043' ),
(56, 'PSA1_ENG_USA_061', 'Face Study (USA_061)','psa1_USA_061', 'PSA1 Study: USA_061' ),
(57, 'PSA1_ENG_USA_113', 'Face Study (USA_113)','psa1_USA_113', 'PSA1 Study: USA_113' ),
(58, 'PSA1_ENG_USA_117', 'Face Study (USA_117)','psa1_USA_117', 'PSA1 Study: USA_117' ),
(59, 'PSA1_ENG_USA_039', 'Face Study (USA_039)','psa1_USA_039', 'PSA1 Study: USA_039' ),
(60, 'PSA1_ENG_USA_055', 'Face Study (USA_055)','psa1_USA_055', 'PSA1 Study: USA_055' ),
(61, 'PSA1_ENG_USA_030', 'Face Study (USA_030)','psa1_USA_030', 'PSA1 Study: USA_030' ),
(62, 'PSA1_ENG_USA_026', 'Face Study (USA_026)','psa1_USA_026', 'PSA1 Study: USA_026' ),
(63, 'PSA1_ENG_USA_027', 'Face Study (USA_027)','psa1_USA_027', 'PSA1 Study: USA_027' ),
(64, 'PSA1_ENG_USA_083', 'Face Study (USA_083)','psa1_USA_083', 'PSA1 Study: USA_083' ),
(65, 'PSA1_ENG_USA_114', 'Face Study (USA_114)','psa1_USA_114', 'PSA1 Study: USA_114' ),
(66, 'PSA1_ENG_USA_115', 'Face Study (USA_115)','psa1_USA_115', 'PSA1 Study: USA_115' ),
(67, 'PSA1_ENG_USA_116', 'Face Study (USA_116)','psa1_USA_116', 'PSA1 Study: USA_116' ),
(68, 'PSA1_ENG_USA_034', 'Face Study (USA_034)','psa1_USA_034', 'PSA1 Study: USA_034' );

REPLACE INTO project_items VALUES 
(1, 'set', 1, 1, NULL),
(2, 'set', 1, 1, NULL),
(3, 'set', 1, 1, NULL),
(4, 'set', 1, 1, NULL),
(5, 'set', 1, 1, NULL),
(6, 'set', 1, 1, NULL),
(7, 'set', 1, 1, NULL),
(8, 'set', 1, 1, NULL),
(9, 'set', 1, 1, NULL),
(10, 'set', 1, 1, NULL),
(11, 'set', 1, 1, NULL),
(12, 'set', 1, 1, NULL),
(13, 'set', 1, 1, NULL),
(14, 'set', 1, 1, NULL),
(15, 'set', 1, 1, NULL),
(16, 'set', 1, 1, NULL),
(17, 'set', 1, 1, NULL),
(18, 'set', 1, 1, NULL),
(19, 'set', 1, 1, NULL),
(20, 'set', 1, 1, NULL),
(21, 'set', 1, 1, NULL),
(22, 'set', 1, 1, NULL),
(23, 'set', 1, 1, NULL),
(24, 'set', 1, 1, NULL),
(25, 'set', 1, 1, NULL),
(26, 'set', 1, 1, NULL),
(27, 'set', 1, 1, NULL),
(28, 'set', 1, 1, NULL),
(29, 'set', 1, 1, NULL),
(30, 'set', 1, 1, NULL),
(31, 'set', 1, 1, NULL),
(32, 'set', 1, 1, NULL),
(33, 'set', 1, 1, NULL),
(34, 'set', 1, 1, NULL),
(35, 'set', 1, 1, NULL),
(36, 'set', 1, 1, NULL),
(37, 'set', 1, 1, NULL),
(38, 'set', 1, 1, NULL),
(39, 'set', 1, 1, NULL),
(40, 'set', 1, 1, NULL),
(41, 'set', 1, 1, NULL),
(42, 'set', 1, 1, NULL),
(43, 'set', 1, 1, NULL),
(44, 'set', 1, 1, NULL),
(45, 'set', 1, 1, NULL),
(46, 'set', 1, 1, NULL),
(47, 'set', 1, 1, NULL),
(48, 'set', 1, 1, NULL),
(49, 'set', 1, 1, NULL),
(50, 'set', 1, 1, NULL),
(51, 'set', 1, 1, NULL),
(52, 'set', 1, 1, NULL),
(53, 'set', 1, 1, NULL),
(54, 'set', 1, 1, NULL),
(55, 'set', 1, 1, NULL),
(56, 'set', 1, 1, NULL),
(57, 'set', 1, 1, NULL),
(58, 'set', 1, 1, NULL),
(59, 'set', 1, 1, NULL),
(60, 'set', 1, 1, NULL),
(61, 'set', 1, 1, NULL),
(62, 'set', 1, 1, NULL),
(63, 'set', 1, 1, NULL),
(64, 'set', 1, 1, NULL),
(65, 'set', 1, 1, NULL),
(66, 'set', 1, 1, NULL),
(67, 'set', 1, 1, NULL),
(68, 'set', 1, 1, NULL);

REPLACE INTO project_items VALUES 
(1, 'set', 1, 1, NULL),
(2, 'set', 1, 1, NULL),
(3, 'set', 1, 1, NULL),
(4, 'set', 1, 1, NULL),
(5, 'set', 1, 1, NULL),
(6, 'set', 1, 1, NULL),
(7, 'set', 1, 1, NULL),
(8, 'set', 1, 1, NULL),
(9, 'set', 1, 1, NULL),
(10, 'set', 1, 1, NULL),
(11, 'set', 1, 1, NULL),
(12, 'set', 1, 1, NULL),
(13, 'set', 1, 1, NULL),
(14, 'set', 1, 1, NULL),
(15, 'set', 1, 1, NULL),
(16, 'set', 1, 1, NULL),
(17, 'set', 1, 1, NULL),
(18, 'set', 1, 1, NULL),
(19, 'set', 1, 1, NULL),
(20, 'set', 1, 1, NULL),
(21, 'set', 1, 1, NULL),
(22, 'set', 1, 1, NULL),
(23, 'set', 1, 1, NULL),
(24, 'set', 1, 1, NULL),
(25, 'set', 1, 1, NULL),
(26, 'set', 1, 1, NULL),
(27, 'set', 1, 1, NULL),
(28, 'set', 1, 1, NULL),
(29, 'set', 1, 1, NULL),
(30, 'set', 1, 1, NULL),
(31, 'set', 1, 1, NULL),
(32, 'set', 1, 1, NULL),
(33, 'set', 1, 1, NULL),
(34, 'set', 1, 1, NULL),
(35, 'set', 1, 1, NULL),
(36, 'set', 1, 1, NULL),
(37, 'set', 1, 1, NULL),
(38, 'set', 1, 1, NULL),
(39, 'set', 1, 1, NULL),
(40, 'set', 1, 1, NULL),
(41, 'set', 1, 1, NULL),
(42, 'set', 1, 1, NULL),
(43, 'set', 1, 1, NULL),
(44, 'set', 1, 1, NULL),
(45, 'set', 1, 1, NULL),
(46, 'set', 1, 1, NULL),
(47, 'set', 1, 1, NULL),
(48, 'set', 1, 1, NULL),
(49, 'set', 1, 1, NULL),
(50, 'set', 1, 1, NULL),
(51, 'set', 1, 1, NULL),
(52, 'set', 1, 1, NULL),
(53, 'set', 1, 1, NULL),
(54, 'set', 1, 1, NULL),
(55, 'set', 1, 1, NULL),
(56, 'set', 1, 1, NULL),
(57, 'set', 1, 1, NULL),
(58, 'set', 1, 1, NULL),
(59, 'set', 1, 1, NULL),
(60, 'set', 1, 1, NULL),
(61, 'set', 1, 1, NULL),
(62, 'set', 1, 1, NULL),
(63, 'set', 1, 1, NULL),
(64, 'set', 1, 1, NULL),
(65, 'set', 1, 1, NULL),
(66, 'set', 1, 1, NULL),
(67, 'set', 1, 1, NULL),
(68, 'set', 1, 1, NULL);

UPDATE project SET intro="In this study you will be asked to complete a very short questionnaire collecting information about, for example, your age. You will then be asked to rate 120 faces on a given trait. After doing so, you will be asked to rate those same faces for the same trait again. Please click on the button below to consent and start the study." WHERE id >=1 AND id <=68;